version: "3.9"
services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: Test1234!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  backend:
    depends_on:
      - sql
    image: powoeuwcrossteamacr.azurecr.io/e_backend:1.0
    ports:
      - "5012:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sql;Database=DefaultDatabase;User Id=sa;Password=Test1234!;
      ConnectionStrings__CoreDbConnection: Server=sql;Database=CoreDatabase;User Id=sa;Password=Test1234!;
