name: Deploy-producer-app

on:
  repository_dispatch:
    types: [build]

  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "Frontend/apps/common-components/**"
      - "Frontend/apps/producer-catering-app/**"
      - "Frontend/producer.Dockerfile"
