name: Deploy-deliverer-app

on:
  repository_dispatch:
    types: [build]

  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "Frontend/apps/common-components/**"
      - "Frontend/apps/deliverer-catering-app/**"
      - "Frontend/deliverer.Dockerfile"
