name: MonitorCluster

on:
  workflow_dispatch:

env:
  NAMESPACE: "f"
  CATERING_API_POD_NAME: "catering-api-5c85cbb6c9-vszbt"
  CLIENT_APP_POD_NAME: "catering-client-app-7bcd87dbc5-7xrhw"

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/setup-kubectl@v1
        with:
          version: "v1.18.8"
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ secrets.AKS_NAME }}
          resource-group: ${{ secrets.AKS_RG_NAME }}
      - name: Get pods
        run: kubectl get pods -n ${NAMESPACE} -o wide
      - name: Get svc
        run: kubectl get svc -n ${NAMESPACE}
      - name: Get ingress
        run: kubectl get ingress -n ${NAMESPACE}
      - name: Get all ingresses
        run: kubectl get ingress -A
      - name: Get all svcs
        run: kubectl get svc -A
      - name: describe api
        run: kubectl logs ${CATERING_API_POD_NAME} -n ${NAMESPACE}
      - name: list env variables for API
        run: kubectl exec ${CATERING_API_POD_NAME} env
      - name: describe app
        run: kubectl logs ${CLIENT_APP_POD_NAME} -n ${NAMESPACE}
