# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with: 
        path: ./Frontend/deliverer-catering-app
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache-dependency-path: './Frontend/deliverer-catering-app/package-lock.json' 
    - name: install
      working-directory: ./Frontend/deliverer-catering-app
      run: npm i 
    - name: tests
      working-directory: ./Frontend/deliverer-catering-app
      run: npm test
#     - name: Resolve
#       working-directory: ./Frontend/deliverer-catering-app
#       run: npm run build --if-present --prefix ./Frontend/deliverer-catering-app
#     - name: Resolve
#       run: npm test --prefix ./Frontend/deliverer-catering-app
#       working-directory: ./Frontend/deliverer-catering-app
