# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  client-app-CI:
    uses: pw-software-engineering/2022_f-team/.github/workflows/react-app-CI-template.yml@main
    with:
      projectPath: ./Frontend/apps/client-catering-app
  producer-app-CI:
    uses: pw-software-engineering/2022_f-team/.github/workflows/react-app-CI-template.yml@main
    with:
      projectPath: ./Frontend/apps/producer-catering-app
  deliverer-app-CI:
    uses: pw-software-engineering/2022_f-team/.github/workflows/react-app-CI-template.yml@main
    with:
      projectPath: ./Frontend/apps/deliverer-catering-app
