name: react-CI-template

on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string

jobs:
  react-app-CI-job:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache-dependency-path: ./Frontend/package-lock.json
      - name: yarn install
        working-directory: ./Frontend/
        run: yarn install
      # - name: npm test
      #   working-directory: ${{inputs.projectPath}}
      #   run: npm test
      # - name: npm run build
      #   working-directory: ${{inputs.projectPath}}
      #   run: npm run build
